name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      DISPLAY: ":1"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install packages
        run: |
          # sudo add-apt-repository main
          # sudo add-apt-repository universe
          # sudo add-apt-repository multiverse
          # sudo apt-get update

          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y wine32 xvfb wine curl xdotool openbox
          # sudo apt-get install -y wine32 curl xdotool
      - name: Run headless tests
        run: ./start.sh
      # - name: Run headless test
      #   uses: GabrielBB/xvfb-action@v1
      #   with:
      #     run: ./test.sh
      #     working-directory: ./ #optional
      #     options: #optional
